### ISSUE TITLE
Add sound effects

### ISSUE THREAD

**Issue by jerometwell** [jerometwell/chimera#4]
Some stupid sound effects would really give this thing some gusto. 

I'll take anything, but here's some suggestions

* creation noise (possibly random from a pool:  the price is right horn, an explosion, various animal noises)
* preamble/buildup sfx: drum roll, suspense music 

I was hoping a library like https://github.com/Marak/play.js might just be able to do this.

**Comment by Adam-STaC-Solutions** [comment]
I'm tangenting this to do a new Issue 👍
